security_monkey/scheduler.py

When adding a new account its necessary to restart scheduler after which it waits the default interval time before next run. If there are setup issues in the new account you'd be waiting for a while to resolve and try again. Hence the simple flag to make it start "now()"
15 minutes could save you... :)

Run job "now()" after a scheduler restart.

---

docs/quickstart.rst
manage.py
security_monkey/common/utils/utils.py

This adds the ability to add accounts via manage.py. This is useful for adding account via config files before starting the scheduler, to prevent manual work and a restart.

Add add_account to manage.py

---

dart/lib/component/search_bar_component/search_bar_component.dart

Fixes issue #163 
Tested with an account name with a "+" in it. This encodes that as %2B.

Added url encoding to distinct callout in search_bar_component

---

security_monkey/auditor.py
security_monkey/auditors/sqs.py
security_monkey/monitors.py

This covers the three basic scenarios:
* Everybody access - *
* Cross account access (document created by 'add a permission' in the console)
* Queue subscribed to SNS Topic (via console)
Let me know if there is any other common uses that I should look for in the policy.

Add SQS Auditor to look for unrestricted access and cross-account access

---

scripts/secmonkey_auto_install.sh

Fix SECURITY_TEAM_EMAIL in auto_install script. If it's written as a string - and not an array - it gets split in to individual characters, causing errors sending emails.

SECURITY_TEAM_EMAIL should be an array

---

security_monkey/common/jinja.py

I noticed that the daily emails were not being sent because it could not find the jinja template. This was because I was not launching the script from the same directory as manage.py.
This fix means that we search for the templates directory relative to the security_monkey.jinja module instead.

Set folder for jinja templates relative to module instead of running path

---

security_monkey/watchers/s3.py

The permissions required for the get_acl call are different than getting the object (s3:GetObjectAcl vs s3GetObject). If these permissions are missing, the call will raise an uncaught exception and crash the watcher/reporter.

Added exception handling around S3 buckets

---

data/aws_accounts.json
manage.py

Fix for #169. Imports known Amazon owned AWS accounts as third-party accounts. Also did a bit of formatting cleanup, making the formatting consistent

Seed Amazon owned AWS accounts

---

docs/dev_setup_ubuntu.rst
docs/quickstart.rst
scripts/secmonkey_auto_install.sh

security_monkey does not build in dart 1.13.  Temporarily we are pinning to 1.12.2-1
Related to #259

Updating docs/scripts to pin to dart 1.12.2-1

---

security_monkey/watcher.py
security_monkey/watchers/elb.py

Refactored the code that handles rate limiting. Longest delay is now 4 seconds, but it will continue trying forever with that delay. Exponential back-on has been removed. 
Wrapped the ELB watcher in a try/except/continue to handle the rare situation where an ELB disappears while you're slurping.

Remove ratelimiting max attempts

---

security_monkey/auditor.py

Found this while tracking down another bug.
I suspect this has been masked by the scheduler only passing in one account at a time and python "leaking" variables out of for loops.
Not a big issue but could cause unexpected behavior.

Fix indentation mistake

---

security_monkey/auditors/elasticsearch_service.py
security_monkey/common/arn.py
security_monkey/common/sts_connect.py
security_monkey/monitors.py
security_monkey/tests/test_arn.py
security_monkey/tests/test_elasticsearch_service.py
security_monkey/watchers/elasticsearch_service.py

This implements and closes out #253.
Allows you to audit AWS ElasticSearch Service domains in your AWS accounts.
This also adds in a feature to the ARN class that allows it to audit IAM ARN's where a `root` account is provided. This is helpful for future audit tweaks.

Added the ElasticSearch Watcher and Auditor (with tests).

---

security_monkey/auditor.py
security_monkey/auditors/elasticsearch_service.py
security_monkey/tests/test_elasticsearch_service.py
security_monkey/watchers/elasticsearch_service.py

- Fixed `i_am_plural` bug in the watcher.
- Added auditor check for Cross-Account Root
- Adjusted ES tests for cross-account checks.
Addresses #283

Fixed cross-account root reporting for ES service

---

security_monkey/watchers/iam/managed_policy.py

By calling the filter twice, we can have the ignorelist filtering
both by name AND by arn.
To ignore AWS default policies, enter the following in 'prefix':
arn:aws:iam::aws:policy/
It can be a fix for #148 .

Tentative for a fix for #148

---

security_monkey/views/account.py

Currently, custom role names are sent but not persisted on account creation. Setting a custom role name works only when updating an account. This updates the POST handler for /api/1/account/<id> to properly save role_name on new accounts.

Persist custom role names on account creation

---

migrations/versions/6b9d673d8e30_added_index_for_itemrevision_created.py
security_monkey/datastore.py
security_monkey/views/item.py

This fixes CPU utilisation issues we were having with our RDS DB. We are only running with 6 technologies and 19 rules but we have over 100 accounts being monitored and lots of changes. We had an m3.large database running at 100% CPU.
By tuning the queries/logic to only return what we need and by adding an index on the date_created field the database CPU now hovers between 2 and 4%. I think I can resize to a smaller DB instance now :)

Tune itemrevision retrievals

---

docs/configuration.rst
docs/quickstart.rst
security_monkey/auditors/elb.py
security_monkey/auditors/rds_security_group.py
security_monkey/auditors/route53.py
security_monkey/auditors/security_group.py
security_monkey/common/utils.py
security_monkey/decorators.py
security_monkey/monitors.py
security_monkey/watchers/iam/iam_role.py
security_monkey/watchers/route53.py
setup.py

Similar to PR #340 (which itself replaced #334).
This PR no longer requires the `route53:gethostedzone` permission.
This uses a library called botor to wrap calls to boto3 which has connection caching and will automatically grab a new connection if the old one is getting close to expiration.
Removed `route53:gethostedzone` from the docs and finished the TODO in the new watcher.

Feature/route53 botor (PR #340 + botor)

---

data/aws_accounts.json

Should partially fix #378 however Amazon have not yet listed the account ID for the ELB logs for the Mumbai region, so we should circle back in a week or two and see if the documentation has been updated by then before closing the issue

Added Mumbai accounts

---

security_monkey/auditors/s3.py

Useful for detecting S3 buckets that are for private use only and incidentally allowing public access by a direct link.

Reports when policy missing from S3.

---

security_monkey/watchers/iam/iam_ssl.py

This is an extension to #396.
@markofu added per-certificate error handling.  I've taken that and added a call to `slurp_exception`, which itself will call `store_exception`, so exceptions can be analyzed by querying the database in addition to checking the logs.

Better handle bad IAM SSL certificates

---

docs/dev_setup_osx.rst

- Added section about XCode
- Added section to fix openssl and cryptography dependency errors.

OS X Install doc updates for El Capitan and higher.

---

docs/configuration.rst
docs/quickstart.rst
scripts/secmonkey_role_setup.py

- The route53 watcher requires access to the `route53domains:getdomaindetail` permission
- Added it to the Quickstart doc.

Added "route53domains:getdomaindetail" to permissions doc.

---

setup.py

Fix for the issue : Jinja2 2.7.2 is installed but Jinja2>=2.8 is required by set(['moto'])
Moto now depends on Jinja2 2.8 - Consider updating to the latest version of Jinja2 2.9?

setup.py fail because of moto lib

---

security_monkey/datastore.py
security_monkey/tests/test_exception_logging.py

Type: Bugfix
Why:
Netflix added code to store exceptions in the database, but when the
method to store the exception is called before the associated tech
type is stored, it throws an error. The error is caught and logged
which would cause false alerts.
Creating the tech type if it doesn't exist

Fix exception logging in store_exception ✅

---

security_monkey/scheduler.py

Type: general-bugfix
With the new version of app scheduler unhandled exceptions are not
recorded unless explicitly configured to do so.
Adding a listener to catch and store unhandled exceptions

Adds exception logging listener for appscheduler

---

.travis.yml
security_monkey/sso/views.py
setup.py

Moved the `python-saml` lib to an extras section.
Also, moved testing libs to their own extras section.
Now, `libxmlsec1-dev` is no longer required.
`.travis.yml` modified to install the `tests` requirements:
- `pip install .[tests]`
If you'd like to use onelogin, you simply need to run these commands:
- `sudo apt-get -qq update`
- `sudo apt-get install -y libxml2-dev libxmlsec1-dev`
- `pip install .[onelogin]`
```
extras_require = {
'onelogin': ['python-saml>=2.2.0'],
'tests': [
'nose==1.3.0',
'mock==1.0.1',
'moto==0.4.25',
'freezegun>=0.3.7'
]
}
```

Moved test & onelogin requirements to the setup.py extras_require section.

---

security_monkey/common/PolicyDiff.py

1) If provided with a string, json.loads() is used, which often means
strings in the extracted structure are of type unicode.  If the same
structure is also provided as a dict, there will often be problems where
a str and a unicode are seen as different objects.  To fix, we simply dump
any datastructures and read them back in with the json lib.
2) The lib was not properly handling null values and was ignoring them entirely
in the output.

Fixing two policy diff cases.

---

setup.py

We should not be impacted by the format string vuln in previous versions of jinja2 as we do not allow for user-supplied format strings.
https://www.palletsprojects.com/blog/jinja-281-released/

Bumping jinja2 to >= 2.8.1. 

---

security_monkey/auditors/iam/iam_role.py

This PR extends #478.
It adds minor fixes.  @robertoriv - Could you review my changes?
I had to remove one of the `self.i_am_singular` lines and replace it with a hardcoded `"IAM Role"` because the nested method definitions could not access self.  (Scope issue?)
I'll try to merge this by Tuesday.

Robertoriv feature/check assume role from unknown

---

security_monkey/watchers/iam/iam_ssl.py

The regression happened after moving from M2Crypto to Cryptography. Should fix issue #251.

Fixing a bug where we stopped raising an issue when we could not obtain a cert issuer

---

security_monkey/templates/security/forgot_password.html
security_monkey/templates/security/login_user.html
security_monkey/templates/security/register_user.html
security_monkey/templates/security/reset_password.html
security_monkey/templates/security/send_confirmation.html
setup.py

This should fix the problems in #494.
You can either pin to `Flask-WTF==0.13.1` or update the templates and use `Flask-WTF>=0.14.2` .  This PR does the latter.

Updating the way we interact with Flask-WTF. Closes Issue #494.

---

security_monkey/common/arn.py

Example statement:
```
{
"Resource": "arn:aws:sqs:<region>:<account_number>:<queue_name>",
"Effect": "Allow",
"Sid": "1",
"Action": "sqs:SendMessage",
"Condition": {
"StringEqualsIgnoreCase": {
"aws:SourceArn": "<some_arn>"
}
},
"Principal": "*"
}
```

Updating ARN.py to look for StringEqualsIgnoreCase in policy condition blocks

---

security_monkey/auditors/kms.py
security_monkey/tests/auditors/test_kms.py

The Netflix merge introduced a two defects:
1) Did not insure condition_accounts was created before used
2) Moved the arn check inside a condition block
Move condition_accounts and arn check to cover all paths

Fix KMSAuditor exceptions

---

dart/lib/component/search_bar_component/search_bar_component.html

Added the ability to search with pressing the `enter` key. This is for the second set of fields in the search component.
The previous behaviour was that you **had** to click the "Search" button. I often found myself hitting the `enter` key in a field and expecting it to search.
I've done this by using ng-keyup, checking if the key pressed was `enter` and calling the search method within the input element.

Add ability to press enter to search in search bar component

---

docs/dev_setup_osx.rst

Update the osx dev doc to get it up-to-date.
The reasons for these changes are below:
Homebrew failed to install using the old URL, returning:
curl: (22) The requested URL returned error: 404 Not Found
New URL (off their website):
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
Trying `pip install virtualenvwrapper` fails because six 1.4.1 is deprecated.
Running `sudo pip install virtualenvwrapper --ignore-installed six` fixes this
"Start the DB in a new shell:" rephrased for clarity to "Open a new shell and start the DB".
When I first went through the doc, I didn't know what `postgres -D /usr/local/var/postgres` did. Based on the instructions, I thought it opened the the DB in a new shell automatically.
After trying to run `nginx` after setting …

Update dev_setup_osx.rst to get it up-to-date

---

manage.py
security_monkey/account_manager.py
security_monkey/views/account.py

We were getting intermittent integrity errors and timeouts when
deleting accounts with many items and issues. This appears to be
caused by SQL Alchemy's method of handling cascading deletes,
which is inefficient and does not appear to handle transactional
locks well, allowing for race conditions.
Deleting accounts and related records with a raw sql query

Optimize SQL for account delete

---

dart/lib/component/settings_component/settings_component.dart
dart/lib/component/settings_component/settings_component.html
dart/lib/model/AccountBulkUpdate.dart
dart/lib/model/hammock_config.dart
dart/lib/security_monkey.dart
manage.py
security_monkey/__init__.py
security_monkey/scheduler.py
security_monkey/tests/core/test_scheduler.py
security_monkey/views/account_bulk_update.py
setup.py

Replaces #534  (Fixes merge conflict.)
from @kalpatel01:
Type: generic-large-feature
We've run into instances where we have wanted to reconfigure watcher run
intervals to improve performance or even remove watchers that were
causing problems. Currently this requires logging into the server and
physically changing the code
Provides a Watcher Config page in Settings and an api where a user can
configure the run interval and the active flag

Add bulk enable and disable account service

---

security_monkey/reporter.py
security_monkey/scheduler.py
security_monkey/tests/core/monitor_mock.py
security_monkey/tests/core/test_reporter.py
security_monkey/tests/core/test_scheduler.py

Type: bugfix
The reporter functionality that looks for auditors that are dependent
on watchers that have changes does not currently apply when watchers
are run in different intervals. This can lead to technology types
not being reaudited when dependencies change
Looking at all monitors when determining which auditors to rerun
Watcher results are now saved as watchers are run, not when all
watchers are complete

Fix reaudit issue for watchers in different intervals

---

security_monkey/tests/core/test_watcher.py
security_monkey/watcher.py

Type: general-bugfix
Any item configuration change (ephemeral or non-ephemeral) causes
Security Monkey to remove existing audit issues, which in turn also
removes and justifications on said issues.  While audit issues are
re-added during the next audit, justifications are lost.
Adding test coverage for watcher class when
there are changes, no changes, and ephemeral
changes.
Ensuring audit issues are preserved when config changes are detected for
any item.

Fix justification preservation bug

---

security_monkey/watchers/vpc/peering.py

The peering watcher was throwing an exception when the name tag
contained unicode characters.
Encoding the name tag before processing

Handle unicode name tags

---

security_monkey/export/__init__.py

Some browsers/environments download export file as plaintext, without
.csv file extension.
Explicitly setting the exported filename to 'security-monkey-items.csv'
as part of the response header.

Explicitly set export filename

---

env-config/config-deploy.py
security_monkey/sso/service.py
security_monkey/sso/views.py
security_monkey/tests/core/test_sso_service.py

Type: generic-feature
Current SSO implementation adds all SSO users with View role.
Supporting group app configurations that will check SSO user profile for
'groups' setting to determine initial role for user, if it's the first
time they're logging in.

Set user role via SSO profile

---

security_monkey/auditors/iam/iam_user.py

Type: generic-feature
This is required in order to allow overriding scores for each of these
issues.
Splitting the check_access_keys method into 2 separate check_ methods,
one for each issue.
None

Split check_access_keys method

---

security_monkey/tests/watchers/vpc/test_subnet.py
security_monkey/watchers/elastic_ip.py
security_monkey/watchers/elasticsearch_service.py
security_monkey/watchers/keypair.py
security_monkey/watchers/rds/rds_security_group.py
security_monkey/watchers/security_group.py
security_monkey/watchers/vpc/subnet.py

There is a known defect with boto that returns a None connection for
us-east-2 (https://github.com/boto/boto/issues/3629)
Moves affected watchers to boto3 connection.
None

Convert watchers to boto3

---

security_monkey/auditors/iam/managed_policy.py
security_monkey/tests/auditors/test_managed_policy.py

Currently, audits are performed against AWS created managed policies.
These checks are not meaningful unless another resource is using the
policy
Only performing policy auditor checks on AWS policies if there is
a resource attached

Reduce AWS managed policy audit noise

---

docs/misc.rst
manage.py
security_monkey/alerters/__init__.py
security_monkey/alerters/custom_alerter.py
security_monkey/auditor.py
security_monkey/datastore.py
security_monkey/watcher.py

This change allows users to customize how they report auditor and
watcher changes during both reporter runs and forced runs of
`audit_changes` and `find_changes`.

Add support for custom watcher and auditor alerters

---

manage.py
security_monkey/account_manager.py
security_monkey/common/audit_issue_cleanup.py
security_monkey/datastore.py
security_monkey/tests/core/test_audit_issue_cleanup.py
security_monkey/views/account.py

Type: generic-feature
In some instances such an an account pattern change or removal
of an auditor, issues are never cleared because the auditor that
created them never gets run against the account.
Adding cleanup methods to be run at build time
Change-Id: I2dc4b24d2a898acb9beb85ba0cd91ad112b0a253

Add functionality to clean up stale issues

---

security_monkey/sso/service.py
security_monkey/sso/views.py

PR #576 allowed for automatically setting user roles based on group membership.
This had an unanticipated impact on our install where user roles were being downgraded to `View` on login.  The reason is that the PR modified existing users as well as new users.  Also, the PR required a new config value `ADMIN_GROUP` / `JUSTIFY_GROUP` be placed into the config file.  Also, the PR checked the SSO response for the keyword `groups`, whereas our SSO returns `googleGroups`.
- I've modified the SSO code to check the profile for both `groups` and for `googleGroups` when using PING.
- I also modified the SSO code to only assign a role for new user creation.  Existing users will not be impacted.  This means the current security_monkey installs won't be required to modify their config file to maintain …

SSO Role modifications

---

security_monkey/common/gcp/util.py
security_monkey/watchers/gcp/gce/firewall.py
security_monkey/watchers/gcp/gce/network.py
security_monkey/watchers/gcp/gcs/bucket.py
security_monkey/watchers/gcp/iam/serviceaccount.py

When the user specified the path to the credentials file, the path wasn't making it's way to the client.  This bug isn't visible unless: 
* one is monitoring GCP from AWS
* one is monitoring GCP using a serviceaccount other than the one used by the instance
Changes made:
* Created new function get_gcp_project_creds utility function build list of creds.
* Updated existing GCP watchers.
* Removed name_to_identifier utility function as it's no longer needed

GCP: fixed issue where client wasn't receiving user-specified creds

---

manage.py

Currently only AWS account is possible to create via CLI.
This patch adds support of discovering available account types and creating CLI subcommands for each account type.
E.g. if we have AWS and OpenStack account types available we will have two additional subcommands:
```
usage: manage.py [-h]
...
add_account_aws     Add AWS account
add_account_openstack
Add OpenStack account
...
```
Sample of custom account usage:
```
$ manage.py add_account_openstack -h
usage: manage.py add_account_openstack [-h] -n NAME [--thirdparty] [--active]
[--notes NOTES] --id IDENTIFIER
[--auth_url AUTH_URL]
[--username USERNAME]
[--password PASSWORD]
[--project_name PROJECT_NAME]
[--project_domain_name PROJECT_DOMAIN_NAME]
[--user_domain_name USER_DOMAIN_NAME]
Add OpenStack account
optional arguments:
-h, …
```

Implement add_account for custom accounts

---

docs/configuration.rst
docs/quickstart.rst
scripts/secmonkey_role_setup.py

ec2 describe_vpn_gateways seen here:
https://github.com/Netflix/security_monkey/pull/406/files#diff-f7287dd9026a529b5d1a3932687f2cfaR57

Added permission for DescribeVpnGateways missing for #406

---

security_monkey/auditors/elb.py

Using the correct name for the imported method:
`from security_monkey.common.utils import check_rfc_1918`
Fixes #604

Fixing reference to check_rfc_1918

---

security_monkey/datastore.py
security_monkey/views/distinct.py

This solves #548.
The search dropdowns have gotten pretty slow.
I had SQLAlchemy print out the actual SQL it was sending to the DB and determined the `Item.issue_count` column_property was causing a significant delay.  I've modified that column property to be deferred.
The many joins were also having a big impact.  I've moved the joins to occur only when they are actually needed.  We've seen between a 10x and a 30x improvement with these modifications.
(Adding an index to Technology.name in #610 may have also helped, though I'm not sure by how much.)

Setting Item.issue_count to deferred.  Only joining tables in distinct if necessary.

---

docs/quickstart.rst
manage.py

The default gunicorn timeout is 30 seconds.
The proxy timeout value we were passing to nginx was 120 seconds.
This PR sets both to 1800 seconds which is far longer than should ever be required.
Note: ELB's enforce a default timeout of 60s. If you need more time, you'll need to edit the ELB in the console.

Increasing default timeout

---

security_monkey/common/gcp/config.py
security_monkey/common/gcp/util.py
security_monkey/watchers/gcp/gce/firewall.py
security_monkey/watchers/gcp/gce/network.py
security_monkey/watchers/gcp/gcs/bucket.py
security_monkey/watchers/gcp/iam/serviceaccount.py

Set the user_agent.  The version of Security Monkey is currently hard-coded, but hidden by a function call, so it can be abstracted later on.
This PR requires Netflix-Skunkworks/cloudaux#25 to be installed.

GCP: set User Agent

---

manage.py
migrations/versions/908b0085d28d_.py
security_monkey/tests/views/__init__.py

**Note:** This has an alembic DB script that will find all unencrypted DB passwords, and **DELETE THE PASSWORDS FOR THE USER**.
_**The user must use the recover password feature if affected**._

Fix for plaintext passwords in DB if using CLI for user creation 😱

---

security_monkey/watchers/acm.py

This fixes an exception when dealing with an imported ACM certificate.
```
2017-03-20 19:14:04,080 ERROR: Job "run_change_reporter (trigger: interval[0:15:00], next run at: 2017-03-20 19:18:08.450588)" raised an exception [in build/bdist.linux-x86_64/egg/apscheduler/scheduler.py:520]
Traceback (most recent call last):
File "build/bdist.linux-x86_64/egg/apscheduler/scheduler.py", line 512, in _run_job
retval = job.func(*job.args, **job.kwargs)
File "/usr/local/src/security_monkey/security_monkey/scheduler.py", line 32, in run_change_reporter
reporter.run(account, interval)
File "/usr/local/src/security_monkey/security_monkey/reporter.py", line 61, in run
monitor.watcher.save()
File "/usr/local/src/security_monkey/security_monkey/watcher.py", line 364, in save
item.save(self.datastore)
File …
```

Fix ACM certificate ImportedAt timestamp

---

docs/misc.rst
security_monkey/alerters/custom_alerter.py

There little typo in docs and signature. Method report_auditor_changes receive auditor instance, not items list.

Fix docs and variable names related to custom alerters

---

security_monkey/watchers/s3.py

If MFA is enabled on the bucket we can't retrieve the ACL. This just logs a warning and carries on. It should also fix issue #579 when an ACL doesn't actually exist or has been deleted.

Log Warning when S3 ACL can't be retrieved.

---

dart/lib/component/issue_table_component/issue_table_component.dart
dart/lib/component/issue_table_component/issue_table_component.html
dart/lib/component/item_table_component/item_table_component.dart
dart/lib/component/justified_table_component/justified_table_component.dart
dart/lib/component/justified_table_component/justified_table_component.html
dart/lib/component/revision_table_component/revision_table_component.dart
dart/lib/component/revision_table_component/revision_table_component.html
security_monkey/views/item.py
security_monkey/views/item_issue.py
security_monkey/views/revision.py

Filtering on Account Type wasn't working correctly and had not been added to several screens.  By extension, I believe this should resolve #577.
Filtering added to:
* Audit Issues
* Justified Issues
* Items plus Historical Changes

GCP: fixed UI Account Type filtering

---

security_monkey/export/__init__.py

Fixes #645 by removing Account.s3_name from the exported CSV and renaming Account.number to Account.identifier.

Removing s3_name from exporter and renaming Account.number to identifier

---

Dockerfile
dart/pubspec.yaml
docker/nginx/Dockerfile
docs/authors.md
docs/changelog.md

v0.9.0 (2017-04-13)
----------------------------------------
- PR #500 - @monkeysecurity - Updating ARN.py to look for StringEqualsIgnoreCase in policy condition blocks
- PR #511 - @kalpatel01 - Fix KMSAuditor exceptions
- PR #510 - @kalpatel01 - Add additional JIRA configurations
- PR #504 - @redixin - Plugins support
- PR #515 - @badraufran - Add ability to press enter to search in search bar component
- PR #514 - @badraufran - Update dev_setup_osx.rst to get it up-to-date
- PR #513 / #545- @mikegrima - Fix for S3 watcher errors.
- PR #516  - @badraufran - Remove broken packages link
- PR #518 - @badraufran  - Update `dev_setup_osx` (Remove sudo)
- PR #519 - @selmanj - Minor reformatting/style changes to Docker docs
- PR #512 / #521 - @kalpatel01 - Organize tests into directories
- PR …

Changelog updates 090

---

setup.py

Use find_packages in setup.py to include nested packages.
Closes #665

Fix missing packages in setup.py

---

security_monkey/auditors/elb.py

This resolves the 'Unknown reference policy' ELB auditor issue for these AWS-provided ELB policies.

Add reference_policies for TLS transitional ELB security policies

---

migrations/versions/b8ccf5b8089b_.py

I'm unsure why this DB migration has caused reports of `monkey db upgrade` stalling.
I've no-op'd this DB migration.  It wasn't modifying the data structure, just the content.
Instead, we recommend calling `monkey fetch_aws_canonical_ids`.

No-opping DB migration b8ccf5b8089b

---

security_monkey/watchers/iam/managed_policy.py

The AWS IAM watcher attempts to list attachments for all policies within an account for users, groups, and roles. This causes a minimum of three calls to iam:ListEntitiesForPolicy for every policy even if the attachment count for a policy is zero. This change reduces the number of calls by checking the attachment count of a policy before listing the attached entities. For accounts with a large number of unused policies or additional tools calling IAM, this prevents unnecessary volume and helps prevent throttling by AWS.

Skip listing attachments for unused IAM policies

---

docs/iam_gcp.md
docs/instance_launch_gcp.md
docs/quickstart.md

Ran through Quickstart again and found some minor updates, the biggest of which is to enable the IAM API.

GCP updates to Quickstart

---

security_monkey/watchers/gcp/iam/serviceaccount.py

DisplayName is an optional field.  Changed to Email for consistency.  This was raised in Gitter chat, but I don't think it was officially reported.

Changed DisplayName to Email in ServiceAccount watcher

---

security_monkey/auditors/kms.py

The default aws/acm KMS policy raises an issue with a score of 5 even though it's fine as-is.
Specifically, it raises this issue:
> An KMS policy where { 'Principal': { 'AWS': '*' } } must also have a {'Condition': {'StringEquals': { 'kms:CallerAccount': '' } } } or it is open to the world.
The policy looks like the following:
```
{
"Resource": "*",
"Effect": "Deny",
"Sid": "Deny encryption or decryption",
"Action": [
"kms:Decrypt*",
"kms:Encrypt*"
],
"Condition": {
"StringEquals": {
"kms:CallerAccount": "[...]"
}
},
"Principal": {
"AWS": "*"
}
},
{
"Resource": "*",
"Effect": "Allow",
"Sid": "Allowed operations for the key owner",
"Action": [
"kms:DescribeKey",
"kms:GetKeyPolicy",
"kms:ListGrants",
"kms:RevokeGrant"
],
"Condition": {
"StringEquals": {
"kms:CallerAccount": "[...]"
}
}, …
```

do not add an issue when "Effect" is "Deny"

---

security_monkey/datastore_utils.py
security_monkey/tests/core/test_datastore_utils.py
security_monkey/tests/core/test_watcher.py
security_monkey/watcher.py
setup.py

Changing batch watchers to set created_items,changed_items,deleted_items so the Alerter fires properly.
Fixes #705

Changing batch watchers to set created_items,changed_items,deleted_items so the Alerter fires properly.

---

env-config/config-docker.py

Format string is failing with TypeError when environment variable
SECURITY_MONKEY_POSTGRES_PORT is set.

Fix type of postgresql port in env-config/config-docker.py

---

security_monkey/sso/views.py

Given that the SSO providers are authenticating the request (by definition), I don't see a need for CSRF on this blueprint. Otherwise, I didn't have a good solution to forward the CSRF token to OneLogin and back :(

Fix for #593 by exempting csrf for SSO

---

security_monkey/common/gcp/util.py
security_monkey/watchers/gcp/gce/firewall.py
setup.py

Version 1.2.2 of Cloudaux changes the modify argument from 'format', to output, which is used by GCP, specifically in firewall.py via our own wrapper.  We removed an unused import to cloudaux.orchestration.modify and updated our modify wrapper to use the new 'output' parameter.
We also set the cloudaux version in setup.py to 1.2.2 to ensure users receive the cloudaux version with this parameter update.
Fixes #720

[GCP] fix modify parameter, remove unused import, upgrade cloudaux version

---

security_monkey/common/gcp/util.py
security_monkey/watchers/gcp/gce/firewall.py
security_monkey/watchers/gcp/gce/network.py
security_monkey/watchers/gcp/gcs/bucket.py
security_monkey/watchers/gcp/iam/serviceaccount.py

Prepend project id string to arn field to avoid key collusions.
Fixes #725.
Two possible concerns here:
* This could make the arn very long.  Not a problem for the db column (Text), but could be for places on screen.
* Anyone using the existing version will end up with different arns after an update.  Still, since GCP functionality is young, might make sense to do it now

update resource_builder to take project argument

---

security_monkey/tests/auditors/gcp/gce/test_firewall.py
security_monkey/tests/auditors/gcp/gce/test_network.py
security_monkey/tests/auditors/gcp/gcs/test_bucket.py
security_monkey/tests/auditors/gcp/iam/test_serviceaccount.py

Some auditor tests for GCP.  These run with pytest like so:
`PYTHONPATH=. pytest security_monkey/tests/auditors/gcp/iam/test_serviceaccount.py`
`PYTHONPATH=. pytest security_monkey/tests/auditors/gcp/gce/test_firewall.py`
`PYTHONPATH=. pytest security_monkey/tests/auditors/gcp/gcs/test_bucket.py`
`PYTHONPATH=. pytest security_monkey/tests/auditors/gcp/gce/test_network.py`

Basic auditor tests for GCP

---

security_monkey/watchers/kms.py

AWS KMS keys don't have user-visible policies, so requesting them via the API
returns an error. The default policy check is moved before the API request
to limit errors from showing up in cloudtrail.
This resolves issue #721

Remove request for AWS KMS key policies

---

security_monkey/auditors/kms.py
security_monkey/watchers/kms.py

The AWS CIS Benchmark recommends that all AWS KMS keys are rotated annually.
This change tracks the rotation state of all KMS keys and create a 1 point
issue when a key is not configured to rotate.
This change requires new permissions in the Security Monkey policy document:
`kms:GetKeyRotationStatus`

Add a KMS key rotation watcher and auditor

---

security_monkey/cloudaux_batched_watcher.py
security_monkey/cloudaux_watcher.py
security_monkey/tests/core/test_scheduler.py

Fixing bug where All S3 buckets were recorded in us-east-1.  The bug was introduced by a recent refactor.  The JSON still contained the correct region, but the table and filters would display an incorrect region.
Allowing S3 to record in the buckets region instead of the region where the initial boto connection takes place (us-east-1).

Fixing S3 Region

---

security_monkey/manage.py

The `manage.py`/`monkey` script currently only supports specifying accounts by their security_monkey-managed name when running tasks such as `find_changes`. This PR adds support for specifying accounts by their id (`acccount.identifier`) and allows for easier integrations with external manual or automated workflows for running tasks that only are aware of the identifier.
```console
$ python manage.py find_changes -a 1234567890 -m s3
```

Allow specifying accounts by id in manage.py

---

docs/dev_setup_osx.md
docs/dev_setup_ubuntu.md

Updated osx/ubuntu guides to match quickstart guide and scripts
* `securitymonkeydb` -> `secmonkey`
* `securitymonkeypass` -> `securitymonkeypassword`

fix docs inconsistency in default db/schema name and password

---

dart/web/ui.html
security_monkey/auditors/s3.py

This PR closes 3 issues:
- Improves the reports dropdown (#539).
- #342 - s3 auditor should better handle conditions 
- #641 - S3 auditor needs source vpce exemption
S3 bucket policies with a wildcard principal 
- `POLICY - This Policy Allows Conditional Access From Anyone.` with score of 3.  Will stuff the condition keys into the notes section like `IpAddress/aws:SourceIp` or `StringEquals/aws:sourceVpce` or `StringLike/aws:Referer`.
- `POLICY - This Policy Allows Access From Anyone.` with a score of 10

Improving S3 Auditor and reports dropdown.

---

security_monkey/manage.py

Use proper arguments for filter_by:
Traceback (most recent call last):
File "./venv/bin/monkey", line 11, in <module>
load_entry_point('security-monkey', 'console_scripts', 'monkey')()
File "/home/ubuntu/security_monkey/security_monkey/manage.py", line 625, in main
manager.run()
File "/home/ubuntu/venv/local/lib/python2.7/site-packages/flask_script/__init__.py", line 397, in run
result = self.handle(sys.argv[0], sys.argv[1:])
File "/home/ubuntu/venv/local/lib/python2.7/site-packages/flask_script/__init__.py", line 376, in handle
return handle(app, *positional_args, **kwargs)
File "/home/ubuntu/venv/local/lib/python2.7/site-packages/flask_script/commands.py", line 145, in handle
return self.run(*args, **kwargs)
File "/home/ubuntu/security_monkey/security_monkey/manage.py", line 97, in …

Fix unjustified issues deletion

---

dart/web/ui.html
security_monkey/auditors/elb.py
security_monkey/auditors/elbv2.py
security_monkey/auditors/vpc/vpn.py
security_monkey/watchers/elbv2.py
setup.py

- Updating Report dropdowns.
- Adding ephemeral section to ALB watcher.
- Bumping cloudaux to 1.3.1
- Fixing syntax errors in VPN Auditor.
- Adding ALB Auditor
- Spitting "Accessible from non-private CIDR" out of "Internet Accessible" for ELBs and ALBs.
(Internet Accessible for ELBs/ALBs now means access from `/0` explicitly.)

Alb auditor

---

docs/quickstart.md

Missing second letter 'L' in SQLACHEMY_DATABASE_URI.
Should be SQLALCHEMY_DATABASE_URI

TYPO IN SQLACHEMY_DATABASE_URI

---

security_monkey/account_manager.py
security_monkey/account_managers/aws_account.py

Initial stab at fixing #783
All account identifiers will be stripped() of leading/trailing white space.
AWS identifiers will have hyphens removed.

Sanitizing account identifiers.

---

.gitignore

To allow easy overriding of docker environment and configuration.

add docker-compose.override.yml to .gitignore

---

security_monkey/watchers/ec2/ec2_instance.py

Fix for the issue https://github.com/Netflix/security_monkey/issues/798
Bug: Instance count information was getting incorrectly recorded
Problem: After retrieving instances using AWS API, instances list was iterated twice in loop. This lead to duplicating results and missing some other ones

Ec2instance watcher issue798

---

security_monkey/watchers/github/repo.py

Added "webhooks ... last_response" in GH Repo watcher as ephemeral field.
This can case a lot of noise if a webhook is unstable.

Added "webhooks ... last_response" in GH Repo Watcher as ephemeral field

---

dart/web/ui.html
security_monkey/auditor.py
security_monkey/auditors/rds_snapshot.py
security_monkey/auditors/resource_policy_auditor.py
security_monkey/tests/auditors/test_rds_snapshot.py
security_monkey/watchers/rds/rds_snapshot.py

- Requires new permission: `rds:describedbsnapshotattributes`
- Updates RDS Snapshot watcher to save the snapshot attributes.  (Share data is stored in attributes.)
- Adds a new auditor that checks for `all` or checks the account identifiers for friendly, thirdparty, or unknown cross account access.
- Adds tests for the new auditor.
- Refactors `OBJECT_STORE` out of ResourcePolicyAuditor and into the parent Auditor so the data can be used with any auditor.

Adding RDS Snapshot Auditor.

---

env-config/config.py

Hi @monkeysecurity, we should merge this pull request as it fixes an error in my previous PR, ACTIVE_PROVIDERS was initialized to [''] when it should have been left as an empty list []

Fix: ACTIVE_PROVIDERS was initialized by mistake

---

migrations/versions/5bd631a1b748_.py
security_monkey/datastore.py
security_monkey/scheduler.py
security_monkey/watcher.py

The DB migration in PR #825 did not set the `fixed` flag, leaving it null.
As a result, the UI would not display these migrated issues.
This adds a new DB migration that sets `fixed` to `False` wherever it is `null`.  It also makes the field not-nullable.
Also adjusted a few logging levels to make the logs easier to monitor.

Fixing 'fixed' flag. Changing some logging levels.

---

security_monkey/auditors/elb.py

Specifically, if ListenerDescriptions and PolicyDescriptions are missing, this will raise a NoneType is not iterable exception.

Set default .get value when ELB config items missing

---

env-config/config-docker.py
env-config/config-local.py
env-config/config.py
security_monkey/auditor.py
security_monkey/templates/jinja_audit_email.html

Added a new config variable:
`EMAIL_AUDIT_REPORTS_INCLUDE_JUSTIFIED = True`
The default is to send justified issues in the emails.  This can be set to `False`.
This PR also tells SM not to email "fixed" issues.

Fixing issue #844. Optionally removing fixed and justified issues from email reports.

---

docs/iam_aws.md
scripts/secmonkey_role_setup.py

Just a typo in the docs as far as I can see.

rds:describedbsnapshotattributes was missing from the policy

---

env-config/config.py
security_monkey/auditor.py
security_monkey/auditors/iam/iam_group.py
security_monkey/auditors/iam/iam_policy.py
security_monkey/auditors/iam/iam_role.py
security_monkey/auditors/iam/iam_user.py
security_monkey/auditors/iam/managed_policy.py
security_monkey/auditors/resource_policy_auditor.py
security_monkey/tests/auditors/test_iam.py
security_monkey/tests/auditors/test_resource_policy_auditor.py
setup.py

Refactor IAM policy Auditor to use categories and PolicyUniverse parsing logic.
TODO:
Depends on https://github.com/Netflix-Skunkworks/policyuniverse/pull/5
(Tests will likely break until that PR is merged and a new version pushed to pypi.)

Refactor IAM policy Auditor

---

dart/web/ui.html
security_monkey/auditor.py
security_monkey/auditors/elb.py
security_monkey/auditors/elbv2.py
security_monkey/tests/auditors/test_elb.py
security_monkey/tests/auditors/test_elbv2.py

ELBs and ALBs should link to their security groups where appropriate.
This will allow ELBs/ALBs to show issues for `Internet Accessible`, `Friendly Cross Account`, `Thirdparty Cross Account`, and `Unknown Access`.
The UI dropdowns have been updated accordingly.
TODO:

Link ELB/ALB issues to related security groups where appropriate

---

docs/quickstart.md
security_monkey/common/utils.py

Every `monkey` command loads all the modules (auditors/watchers), across all account_types. Instead of requiring all the dependency cloudaux extras to be installed regardless of the account_type of the instance, catch ImportError exceptions in the module load. Both load failures and successes are logged at DEBUG.

Only require account_type specific dependencies be installed

---

security_monkey/watchers/iam/iam_ssl.py

Converted `cert.serial` to `cert.serial_number` because `cert.serial` has been deprecated and replaced by `cert.serial_number`.
For more clarity, I receive an error message when running
monkey find_changes -a account -m iamssl
is
/opt/security_monkey/security_monkey/watchers/iam/iam_ssl.py:75: DeprecationWarning: Certificate serial is deprecated, use serial_number instead.

cert.serial has been deprecated & replaced by cert.serial_number

---

scripts/secmonkey_auto_install.sh

The only entry in the FAQ is to resolve an issue with the minimum number of file handlers -- bumping this limit in the auto install script so that fewer people run into the error.

Bump minfds limit to resolve

---

security_monkey/manage.py

We're using [SWAG](https://github.com/Netflix-Skunkworks/swag-client) but don't define services on all of our accounts. Some of them look like this:
```
{
"aliases": ["alias"],
"contacts": [],
"description": [],
"email": "",
"id": "86753098675",
"name": "oh yes",
"owner": "ukno",
"provider": "aws",
"sensitive": true
}
```
SWAG spec says that the services key is optional: https://github.com/Netflix-Skunkworks/swag-client/blob/538366cedfe8536fc24705f3439a4d16a5e7dc7c/swag_client/schemas/v2.py#L55
So this PR fixes the following error and allows the command to complete:
```
$ monkey sync_swag -b our-bucket -p the-goods.json -o ukno                                              
Traceback (most recent call last):
File "/usr/local/src/security_monkey/venv/bin/monkey", line 11, in <module> …
```

fix KeyError when services in SWAG account is not defined

---

.gitignore
docs/autostarting.md
supervisor/security_monkey_scheduler.conf
supervisor/security_monkey_workers.conf

Changes for runtime files and PYTHON_EGG_CACHE configs, storing both under /usr/local/src/security_monkey (or install root). 
Initially planned on using /var/run for celery runtime (schedule and pidfile), but remembered that /var/run gets cleaned out on a reboot and would require some manual sudo creation/chmod on a restart (or some init.d script). Added instructions to chmod g+w so www-data can create the files in the install root dir and added to .gitignore
For PYTHON_EGG_CACHE, which is needed on workers to store sqlalchemy files, initially in /tmp, which may get cleaned out at some interval by the OS and cause issues, storing in /usr/local/src/security_monkey/.python-egg (which appears to be somewhat of a convention if not in $HOME) and added to .gitignore.

Quickstart updates for celery runtime files

---

security_monkey/exceptions.py
security_monkey/sso/views.py

Setting up two exceptions to help debugging when setting up Google authentication.
First exception happens when configuration is not set up properly. 
Second avoids a weird case where the user gets a valid logged in session, but is still considered anonymous.

Raise better errors during Google Auth faillure

---

security_monkey/manage.py

We sometimes require different role names than the default `SecurityMonkey` but we're using SWAG to sync up accounts. I made `role_name` the one true SWAG service key like so:
```json
"services": [
{
"name": "security_monkey",
"status": [
{
"region": "all",
"enabled": true,
"role_name": "MyBigFatGreekRole"
}
]
}
]
```
Complexity lint yelled at me about that for-for-if-for-if chain, so I also turned the services list into a dict keyed by name. Let me know if that's not good!

allow SWAG to load a custom role name while also refactoring sync_swag

---

docs/misc.md
security_monkey/manage.py
security_monkey/tests/utilities/test_sync_network.py

Implements #938 - I added the `--authoritative` option to allow folks to keep the whitelist tidy.
Tested on a Python 2.7 deployment.

Import network whitelists with the sync_networks command

---

security_monkey/auditor.py

Forcing reload when the db_item object has no issues.
It seems some items contain the db_item field, but they are not loading the current issues, and it can end up spamming the alerters

During audit, enforce item reload if there are no existing issues setted

---

Dockerfile
docker/nginx/Dockerfile

Fixes #959 
This ensures that regardless of your shell umask, the files installed into the built Docker image are reasonable.

Ensure file modes are reasonable

---

dart/lib/component/settings/watcher_config_component/watcher_config_component.html
security_monkey/task_scheduler/beat.py
security_monkey/tests/scheduling/test_celery_scheduler.py
security_monkey/watcher.py

Added an option to have watchers with 0 interval -- this is useful if you want an external cron job to execute it via the `monkey find_changes` command instead of celery.
The use case here is for monitoring GitHub which has very small rate limits. This is useful for things you can't really use Celery for.

Zero-interval watcher support

---

security_monkey/alerter.py
security_monkey/auditor.py
security_monkey/auditors/s3.py
security_monkey/decorators.py
security_monkey/manage.py
security_monkey/task_scheduler/tasks.py
security_monkey/tests/core/test_exception_logging.py
security_monkey/views/account_pattern_audit_score.py
security_monkey/views/audit_scores.py
security_monkey/views/ignore_list.py
security_monkey/views/item_comment.py
security_monkey/views/revision_comment.py
security_monkey/views/users.py
security_monkey/views/watcher_config.py
security_monkey/views/whitelist.py
setup.py

__unicode()__ was removed in Python 3 because all str are Unicode so this PR:
* Changes all calls to __unicode()__ into calls to [__six.text_type()__](https://pythonhosted.org/six/#six.text_type)
* Change all instances of __(str, unicode)__ to [__six.string_types__](https://pythonhosted.org/six/#six.string_types)
* Change remaining instances of __unicode__ to [__six.text_type__](https://pythonhosted.org/six/#six.text_type)
__basestring__ was removed in Python 3 so for each Python file that contains __basestring__, this PR adds __from six import string_types__ and replaces __basestring__ with __string_types__.
The builtin __reload()__ was moved into [importlib](https://docs.python.org/3/library/importlib.html#importlib.reload) in Python 3 because it was being overused and led to odd …

fix-basestring-reload-unicode-for-Python3

---

.travis.yml
setup.py

Add Python 3 testing to Travis CI.  Given that these are early daze, lets leave it in __allow_failures__ mode until we get the kinks worked out.  Also added some key falke8 tests to find undefined names (like __unicode__ in Python 3) and Syntax Errors (like legacy style print statements).  PyLint and Bandit do _not_ find undefined names.

Travis CI: Add Python 3 in allow_failures mode

---

security_monkey/auth/modules.py
security_monkey/manage.py
security_monkey/sso/service.py
security_monkey/sso/views.py
security_monkey/views/account_config.py
security_monkey/views/account_pattern_audit_score.py
security_monkey/views/audit_scores.py

This RP fixes all ExtDeprecationWarning except those which inside `/path/to/code/file/lib/python2.7/site-packages/`.
I suppose that upgrading our requirements(https://requires.io/github/cclauss/security_monkey/requirements/?branch=develop) should go in one of next PRs. #976

Fix flask deprecation warnings #976 

---

security_monkey/auditors/github/repo.py

This PR clears up one of the tests by converting __my_dict.itervalues()__ --> __six.itervalues(my_dict)__.
One file that is problematic is __security_monkey/tests/auditors/test_resource_policy_auditor.py__ because its tests hang so you can not see the results of any of the tests.  There are two tests that fail __outside__ of that file:
* One about a [dictionary changing size during iteration](https://travis-ci.org/Netflix/security_monkey/jobs/349831772#L1912) which Python 3 does not allow and
* One about [bytes vs. strings](https://travis-ci.org/Netflix/security_monkey/jobs/349831772#L1957) which Python 3 is much more strict about.

Try to pass the pytests on Python 3

---

security_monkey/common/PolicyDiff.py

__basestring__ and __unicode__ were remove from Python 3 because all __str__ are Unicode so this PR created equivalents.

Convert PolicyDiff to Python 3

---

security_monkey/task_scheduler/tasks.py
security_monkey/tests/scheduling/test_celery_scheduler.py

- Currently addresses issues where account names get changed. Instead of raising exceptions, it logs an error message that the account will be skipped over
More work is needed to fully address #1005

Some database error fixes

---

security_monkey/decorators.py

Helps avoid `NoneType` exceptions in the `record_exceptions` decorator.

Potential fix in `record_exception()`

---

.travis.yml
docs/autostarting.md
docs/tuneworkers.md
security_monkey/celeryconfig.py
security_monkey/manage.py
security_monkey/task_scheduler/util.py
security_monkey/tests/scheduling/test_celery_scheduler.py
security_monkey/views/user_settings.py
setup.py

Possible fix for notifications bug in #998

---

Dockerfile
docker/nginx/Dockerfile
requirements.txt

Fixing the builds.
Pinned Flask to version 0.12.2, and also fixed Docker pulling in Bionic.
Changes made to the `Dockerfile` should work properly with Bionic, but we will need to spend additional time with Bionic to see what other changes will need to happen for SM to work properly on it.
For now, users are recommended to utilize Xenial (16.04).

Fixing Travis CI build

---

docs/docker.md

Remove reference to virtualenv since it's not in the Dockerfile anymore

Remove reference to virtualenv

---

security_monkey/views/item.py

Introduced (partially) in #872. You can't filter on a table that hasn't
been properly joined.
This issue causes the `active` filter to return `1/N` results, where `N` is the number of active accounts.
Also, you can't join the same table several times, so the existing code
would have also broken if account and accounttype were filtered at the
same time.
So, pull the join out, and invoke it when anyone needs it.

Fix account join issue

---

docker/api-init.sh

Quick small fix. Removes call to virtualenv, since they were removed from the docker environment. Also set the script to explode on errors, to prevent zombie containers.

Fix docker init after docker changes

---

.travis.yml

Pinning openstacksdk to 0.9.18 and os-client-config to 1.28.0 (which is floating dependency), as is root cause of test failures.

Pin openstacksdk versions

---

docs/autostarting.md
security_monkey/task_scheduler/tasks.py

This commit adds an option to SM to post metrics to a queue.  If
configured, the given queue will have messages sent when items
are seen, and then again after items have completed auditing.

Add options to post metrics to queue

---

security_monkey/auditors/openstack/openstack_security_group.py
security_monkey/auditors/security_group.py
security_monkey/tests/auditors/openstack/test_openstack_security_group.py
security_monkey/tests/auditors/test_security_group.py
security_monkey/watchers/openstack/network/openstack_security_group.py
security_monkey/watchers/openstack/object_store/openstack_object_container.py

- Handle null cidrs for Rackspace Internet accessible security groups with unit tests
- Officially add #1039 fix to OpenStack security group auditor with unit test
- Fix singular/plural names in a few OpenStack watchers

Enhancements for OpenStack security group auditor
