Netflix/security_monkey

- docs/api/index.rst
- docs/changelog.rst
- security_monkey/alerter.py
- security_monkey/auditor.py
- security_monkey/reporter.py
- security_monkey/scheduler.py
- security_monkey/templates/jinja_change_item.html
- security_monkey/watcher.py
- setup.py
The changelog has all the updates.
> Merging v0.3.1 to master

- docs/contributing.rst
I followed the MAC instructions but they didn't work so I had to make some modifications. This pull request includes those minor modifications.
> Typo & minor corrections on postgres commands

- dart/lib/component/itemdetails/itemdetails.html
- requirements.txt
- security_monkey/auditor.py
- security_monkey/auditors/security_group.py
- security_monkey/reporter.py
- security_monkey/scheduler.py
- security_monkey/watcher.py
- security_monkey/watchers/iam_user.py
- security_monkey/watchers/security_group.py
> [RFC] Link sgs to related instances

- docs/quickstart.rst
> Fixed quickstart typo

- security_monkey/auditor.py
- security_monkey/templates/jinja_audit_email.html
> Fix missing justification in audit emails and add some colour :)

- security_monkey/watchers/s3.py
So we can potentially write rules against it
> Add S3 logging configuration

- scripts/secmonkey_auto_install.sh
Use currently implemented random value generation technique to create random Salt and Secret_Key
> Remove static secrets

- scripts/secmonkey_auto_install.sh
Fix extension of Supervisor configuration file (conf not ini)
Fix package dependencies (add yaml and swig)
Build static content (from documentation - install dart, build content, deploy)
> Update secmonkey_auto_install script

- requirements.txt
- security_monkey/tests/test_iam.py
- security_monkey/watchers/iam/iam_ssl.py
- setup.py
> Ripping out M2Crypto in favor of cryptography

- scripts/secmonkey_auto_install.sh
This makes the auto-install a bit more robust
> Fix install order

- dart/lib/component/compare_item_revisions/compare_item_revisions.dart
- dart/lib/component/compare_item_revisions/compare_item_revisions.html
- dart/lib/component/item_table_component/item_table_component.dart
- dart/lib/component/item_table_component/item_table_component.html
- dart/lib/component/revision_table_component/revision_table_component.dart
- dart/lib/component/revision_table_component/revision_table_component.html
- dart/lib/model/Item.dart
- dart/lib/model/Revision.dart
- dart/lib/routing/securitymonkey_router.dart
- dart/lib/security_monkey.dart
- dart/web/css/main.css
- dart/web/views/compare_item_revisions.html
This allows you to check for consistency with IAM roles across accounts or between security groups across different regions.
> Adding ability to select up to four items or revisions to be compared

- scripts/secmonkey_auto_install.sh
Tided up the introductory section to reflect updates by cbarrac & updated version number.
Aesthetic changes.
> Tided up the introductory section to reflect updates by cbarrac 

- security_monkey/watcher.py
- security_monkey/watchers/sns.py
Checks if the SNS topic is in the ignore list by name -- not ARN.
> Made fix to SNS ignore list, and PEP8 fixes.

- scripts/secmonkey_auto_install.sh
- additional package dependencies
- additional dart step (get)
Fixes
- correct name expansion in hosts
- handle existing DB
> Update for v0.3.8

- security_monkey/watchers/security_group.py
> Add egress security groups

- security_monkey/watchers/elb.py
Fixes #162 
Sometimes, we get a 400 response. Retrying a few times seems to usually work.
Just in case, we'll use the policy name only to avoid a keyerror
> Retry on elb policy slurp

- security_monkey/auditors/sns.py
- security_monkey/auditors/sqs.py
- security_monkey/common/arn.py
- security_monkey/tests/test_arn.py
Sync with `master` and adds fix for #222
> Fix for Issue #222

- security_monkey/watchers/sns.py
> Fix for underscores not being detected in SNS auditor.

- scripts/secmonkey_auto_install.sh
Created new functions around error notifications and usage messages.
> New error and echo functions to simplify code

- docs/quickstart.rst
> Add DescribeInstances to quickstart role documentation

- security_monkey/common/sts_connect.py
- security_monkey/watchers/elb.py
Reduces code and works with new AWS technologies without code modifications.
> Refactored sts_connect to dynamically import boto resources.

- data/aws_accounts.json
Added the newly available Seoul region (ap-northeast-2) to the AWS Accounts import data
> Added Seoul region IDs to import scripts

- security_monkey/datastore.py
Kill off the thread by raising exception
> Recover from database connection error

- docs/options.rst
- docs/quickstart.rst
- security_monkey/__init__.py
> Log to stderr in the same format when LOG_FILE is unset or None

- security_monkey/scheduler.py
I was having a lot of problems where losing network connection to the database during a transaction causing everything to stop working. Catching those exceptions and cleaning up the session seems to have fixed those issues.
> Handle database exceptions by cleaning up session.

- security_monkey/views/item.py
Disabling an issue under settings/Auditor Settings will now have the intended affect.
(About time?)
> Item List and Item View will no longer display disabled issues. 

- security_monkey/watchers/redshift.py
Makes the redshift watcher less noisy during maintenance periods.
> Fixes #292 - adds ephemeral sections to the redshift watcher

- .gitignore
- docs/dev_setup_osx.rst
- docs/dev_setup_ubuntu.rst
- docs/quickstart.rst
- Addresses documentation bugs in issue #346
- Added more things to `.gitignore`
:banana:
> Doc fixes and clarifications. Addresses #346.

- security_monkey/auditors/sqs.py
Update to #350 to raise an issue for malformed SQS Policies.
> Ollytheninja bugfix/sqs principle

- data/aws_accounts.json
> Adding Mumbai ELB log info

- security_monkey/auditor.py
- security_monkey/datastore.py
- security_monkey/reporter.py
Auditor will now fix any issues that are not attached to an AuditorSetting
> Auditor will now fix any issues that are not attached to an AuditorSetting

- security_monkey/common/arn.py
- security_monkey/tests/test_arn.py
- Also added in tests for it
Addresses #423
> Fix for ARN parsing of cloudfront ARNs

- security_monkey/auditors/elasticsearch_service.py
> Removed s3 ARN check for ElasticSearch Service.

- dart/lib/component/settings/ignore_list_component/ignore_list_component.dart
- dart/lib/component/settings/ignore_list_component/ignore_list_component.html
- dart/lib/component/settings/network_whitelist_component/network_whitelist_component.dart
- dart/lib/component/settings/network_whitelist_component/network_whitelist_component.html
- dart/lib/component/settings_component/settings_component.dart
- dart/lib/component/settings_component/settings_component.html
- dart/lib/security_monkey.dart
Network Whitelist and Ignore List tables have been broken out into their own components and now support pagination via PaginatedTable.
Resolves #167
> Add pagination for whitelist and ignore list

- .coveragerc
- .travis.yml
Hopefully adding coveralls/coverage to security_monkey.
> [WIP] Coverage

- security_monkey/common/PolicyDiff.py
- security_monkey/tests/test_policydiff.py
Also, some variable refactoring.
> Adding tests for the policydiff module.

- security_monkey/decorators.py
- security_monkey/watchers/s3.py
- setup.py
> Refactoring s3 watcher to use Netflix CloudAux

- dart/lib/routing/securitymonkey_router.dart
- dart/web/ui.html
Moving the Search page back to default and creating a hyperlink to the dashboard.
> Moving the Search page back to default and creating a hyperlink to the dashboard.

- dart/lib/component/item_table_component/item_table_component.dart
- dart/lib/component/search_bar_component/search_bar_component.dart
- dart/lib/component/search_bar_component/search_bar_component.html
- dart/lib/routing/securitymonkey_router.dart
- security_monkey/datastore.py
- security_monkey/views/item.py
> Add support for filtering by item score.

- security_monkey/auditors/iam/iam_user.py
Further fixing the IAM User auditor to work with the new IAM User format.
> Further fixing the IAM User auditor to work with the new IAM User format.

- security_monkey/auditors/kms.py
> Updating KMS Auditor to extract AWS account IDs from the condition block

- manage.py
`amazon_accounts()` broke when we added AccountType.
> Fixing manage.py::amazon_accounts() and adding delete_unjustified_issues()

- security_monkey/auditors/iam/iam_user.py
> Fixes issue 477. Fixes check for "User with password login and no MFA devices."

- security_monkey/auditors/s3.py
> Updating S3 Auditor to use ARN class

- docs/jirasync.rst
- env-config/config-deploy.py
- security_monkey/jirasync.py
* Make JIRA transitions configurable
* Support JIRA proxy settings
* Support JIRA ticket assignee
> Add additional JIRA configurations

- docs/plugins.rst
- manage.py
- security_monkey/common/utils.py
Plugins support via entry_points
Closes: #503
> Plugins support

- security_monkey/tests/test_exception_logging.py
- security_monkey/tests/test_s3.py
- security_monkey/watchers/s3.py
Fix for #506 .  
I would like to add a test case for this before merging it in.
> Fix for S3 watcher errors.

- docs/docker.rst
Current version had some minor typographical issues. Some text rewriting occurred as well.
> Minor reformatting/style changes to Docker docs

- security_monkey/watchers/kms.py
Some kms keys are partially visible but throw exceptions when viewing
details. The current code does not handle these cases so we get false
access errors and do not see the keys.
Handles the access errors and shows partial results.
> Handle known kms boto exceptions

- env-config/config-deploy.py
- env-config/config-docker.py
- env-config/config-local.py
> Usage of GOOGLE_HOSTED_DOMAIN in sample configs

- dart/lib/component/settings_component/settings_component.dart
- dart/lib/component/settings_component/settings_component.html
- security_monkey/views/account.py
Type: generic-feature-enhancement
Improve user interaction with account settings
Add sorting capabilities to the account settings
table
> Add sorting to accounts tables

- security_monkey/watchers/s3.py
Didn't fully fix the issue in #513 .  This should address it.
> Fixed S3 bug (again)

- security_monkey/watchers/elasticsearch_service.py
- Properly fetches ES regions
- Properly handles empty policies
- Fixed bug in exception handler around emtpy policies
> Fixed bugs in the ES watcher 😷

- setup.py
> Upped CloudAux version 📄

- security_monkey/reporter.py
This is code that was removed unintentionally in a recent PR.
Re-adding.
> Re-adding reporter timing information to the logs.

- setup.py
New CloudAux address #574.
A follow up PR will add an ephemeral section as discussed in https://github.com/Netflix-Skunkworks/cloudaux/issues/21.
> Upped CloudAux to 1.1.3 to address #574 🛢️

- security_monkey/watchers/ec2/ec2_instance.py
- security_monkey/watchers/elb.py
- security_monkey/watchers/iam/iam_ssl.py
- security_monkey/watchers/vpc/peering.py
- security_monkey/watchers/vpc/route_table.py
Several watchers had minor defects which caused them to fail in
various situations
Handling the errors
> Fix minor watcher bugs

- security_monkey/auditors/elb.py
DB query will perform a very inefficient table scan on the item table
which could slow down DB performance when the item table gets large. It
is also not the best solution because the security group may not be in
the database.
A better solution would be to add the security group results as a
support watcher and find the security group out of the in memory list.
None
> Replace ELBAuditor DB query with support watcher

- security_monkey/account_managers/gcp_account.py
- security_monkey/auditors/gcp/gce/firewall.py
- security_monkey/auditors/gcp/gce/network.py
- security_monkey/auditors/gcp/gcs/bucket.py
- security_monkey/auditors/gcp/iam/serviceaccount.py
- security_monkey/auditors/gcp/util.py
- security_monkey/common/gcp/config.py
- security_monkey/common/gcp/error.py
- security_monkey/common/gcp/util.py
- security_monkey/watchers/gcp/gce/firewall.py
- security_monkey/watchers/gcp/gce/network.py
- security_monkey/watchers/gcp/gcs/bucket.py
- security_monkey/watchers/gcp/iam/serviceaccount.py
Initial support for Google Cloud Platform.  Basic Watchers/Auditors for ServiceAccounts, Buckets and Networking/Firewall are included.
The issue scores and messages are contained in a configuration class located at security_monkey/common/gcp/config.py
The latest version of Cloudaux is required for this PR.  In addition, PR Netflix-Skunkworks/cloudaux#20 is also required (this has been merged).
(I have some basic unit tests to include in a subsequent PR.)
> [GCP] Watchers/Auditors for GCP

- docs/quickstart.rst
* Made specific AWS and GCP headings
* Added IAM and VM sections for GCP
Docs only change.  No source was modified with this PR.
> GCP docs: Draft of GCP changes

- security_monkey/watchers/gcp/gcs/bucket.py
Depends on Netflix-Skunkworks/cloudaux#24
> GCP: fixed issue where bucket watcher wasn't sending credentials to Cloudaux

- security_monkey/datastore.py
- security_monkey/watchers/s3.py
- setup.py
> Added ephemeral section to S3 for "GrantReferences" ✨

- .gitignore
- security_monkey/auditor.py
- security_monkey/datastore.py
- security_monkey/datastore_utils.py
- security_monkey/monitors.py
- security_monkey/reporter.py
- security_monkey/scheduler.py
- security_monkey/tests/core/monitor_mock.py
- security_monkey/tests/core/test_auditor.py
- security_monkey/tests/core/test_datastore_utils.py
- security_monkey/tests/core/test_reporter.py
- security_monkey/tests/core/test_scheduler.py
- security_monkey/tests/core/test_watcher.py
- security_monkey/tests/watchers/test_iam_role.py
- security_monkey/watcher.py
- security_monkey/watchers/iam/iam_role.py
- Currently supporting IAMRole watcher as a POC.
This is a POC for batching watchers. This is to hopefully alleviate issues with too many files being open for very large workloads with thousands of a particular item.
> Batching support for watchers ⚖️📈

- security_monkey/__init__.py
- security_monkey/common/gcp/config.py
- security_monkey/common/utils.py
- setup.py
Added version property.  Fixes  #617. 
* Added common.utils.`get_version` convenience function
* Updated GCP related code to use get_version
* Borrowed method for reading version from Flask
> Added __version__ property

- security_monkey/watchers/security_group.py
Updated _build_rule and related calls to correct a problem parsing security groups returned via boto3
The function was only returning the first 'IpRanges' and/or 'UserIdGroupPairs' value from the 'IpPermission' and 'IpPermissionEgress' dictionary items. 
If there were multiple list items in 'IpRanges' or 'UserIdGroupPairs', those are not being included in the list of rules.  Each item in these lists should be returned as a separate "rule" entry.
> Fix security group rule parsing (Issue 621)

- dart/lib/component/dashboard_component/dashboard_component.html
Updated the generated links in "Accounts" and "Technology Issue Scores" to properly filter the resulting view.
Corrected the number of URL parameters that are passed.
> Update dashboard view filter links

- .travis.yml
- docs/configuration.rst
- docs/quickstart.rst
- manage.py
- migrations/versions/908b0085d28d_.py
- migrations/versions/b8ccf5b8089b_.py
- security_monkey/account_manager.py
- security_monkey/account_managers/aws_account.py
- security_monkey/auditors/s3.py
- security_monkey/common/s3_canonical.py
- security_monkey/common/utils.py
- security_monkey/tests/auditors/test_s3.py
- security_monkey/tests/utilities/test_s3_canonical.py
> Adding utilities to get S3 canonical IDs. 🆔

- security_monkey/views/account.py
This should make the dashboard results more relevant and load quicker as well.
> Adding active and third_party flags to account view API

- security_monkey/views/account.py
This should resolve account creation and updates in the UI.
Addresses #647
> Fix for UI Account creation bug 🐞

- docker/api-start.sh
- docker/scheduler-start.sh
This PR fixes a little typo introduced in https://github.com/Netflix/security_monkey/pull/657
> [Docker] Typo in the start scripts 🙊

- docs/quickstart.md
- supervisor/security_monkey.conf
Removing lots of `sudo`.
Ran through on a new GCP instance and made some changes for clarity.
> Quickstart GCP Fixes

- security_monkey/auditors/s3.py
* Fix KeyError: 'Principal' error
* and Reduce deep nest
```
2017-03-22 00:06:12,981 ERROR: Job "run_change_reporter (trigger: interval[0:15:00], next run at: 2017-03-22 00:12:55.849921)" raised an exception [in build/bdist.linux-x86_64/egg/apscheduler/scheduler.py:520]
Traceback (most recent call last):
File "build/bdist.linux-x86_64/egg/apscheduler/scheduler.py", line 512, in _run_job
retval = job.func(*job.args, **job.kwargs)
File "/usr/local/src/security_monkey/security_monkey/scheduler.py", line 35, in run_change_reporter
reporter.run(account, interval)
File "/usr/local/src/security_monkey/security_monkey/reporter.py", line 70, in run
auditor.audit_these_objects(items_to_audit)
File "/usr/local/src/security_monkey/security_monkey/auditor.py", line 135, in audit_these_objects …
```
> Fix principal KeyError

- docs/quickupdateguide.md
- docs/update.md
- Added document for How to update existing installation of Security Monkey
- Referenced from https://github.com/Netflix/security_monkey/issues/205 , https://github.com/Netflix/security_monkey/issues/252
> Added doc on update steps

- security_monkey/common/PolicyDiff.py
> Enhancing PolicyDiff to be able to handle non-ascii strings.

- .travis.yml
- security_monkey/manage.py
Should fix #672.
@AlexCline - If you can confirm that this fixes the issue, I'll push a fix to master as well.
> Fixing path to aws_accounts.json

- setup.py
Should fix #673 and #674 
cc @AlexCline
> Adding package_data and data_files sections to setup.py

- security_monkey/sso/views.py
Fixes Issue #501 
Commit the session information (`current_login_at`, `current_login_ip`, etc)
> Commit the security trackable information and refresh user

- .travis.yml
Added parallelization to the Travis builds to hopefully speed them up.
Needed to duplicate everything to disable the "default" build. This is well documented here: https://github.com/travis-ci/travis-ci/issues/4681 (some have had varying success -- this was the only way I could get it to work :/)
> Enhancements to Travis: parallelized the workloads. 🚄

- security_monkey/common/jinja.py
Fix for bug found by @jyukenzan.
> Fixed missing import. 🛃

- security_monkey/datastore_utils.py
- security_monkey/tests/core/test_datastore_utils.py
- security_monkey/tests/core/test_scheduler.py
- security_monkey/tests/core/test_watcher.py
- security_monkey/watcher.py
The emails sent from batched watchers don't contain proper color diffing.  This is an attempt to fix that.
> The emails sent from batched watchers don't contain proper color diffing.  This is an attempt to fix that.

- security_monkey/templates/security/forgot_password.html
- security_monkey/templates/security/login_user.html
- security_monkey/templates/security/register_user.html
- security_monkey/templates/security/reset_password.html
- security_monkey/templates/security/send_confirmation.html
> Fixing path to favicon from flask-security templates

- security_monkey/watcher.py
- security_monkey/watchers/iam/saml_provider.py
- setup.py
Adding SAML Provider CloudAux Watcher. Bumping dependency version of cloudaux.
> Adding SAML Provider CloudAux Watcher. Bumping dependency version of cloudaux.

- security_monkey/__init__.py
- security_monkey/decorators.py
- security_monkey/scheduler.py
- setup.py
> Integrating with sentry.io. (or a locally hosted version)

- security_monkey/watchers/gcp/gce/firewall.py
- security_monkey/watchers/gcp/gce/network.py
- security_monkey/watchers/gcp/gcs/bucket.py
- security_monkey/watchers/gcp/iam/serviceaccount.py
> Use record exception in GCP

- docs/userguide.md
Update and correct SES part of the documentation
> Modify SES documentation

- setup.py
Temporary fix to #786.
Problem caused by:
https://github.com/requests/requests/pull/4223
> Pinning to idna 2.5 to fix dependency problem with requests.

- docs/faq.md
- Added FAQ and Troubleshooting doc. 
- Added steps to resolve 'Too many open files' issue
> Added FAQ and Troubleshooting doc. 

- docs/docker.md
- docs/userguide.md
- security_monkey/manage.py
Rebase #801 on develop branch:
- Changes --number to the new --id
- Moved id up in the options list so that the two required fields appear first
> Fixed some documentation issues

- security_monkey/auditor.py
- security_monkey/auditors/resource_policy_auditor.py
- security_monkey/auditors/security_group.py
Refactor the SecurityGroup Auditor to use the OBJECT_STORE that was originally created in the ResourcePolicyAuditor Refactor.
> Refactor SecurityGroup Auditor

- dart/web/ui.html
- security_monkey/auditors/iam/iam_role.py
- security_monkey/manage.py
Uses multiple inheritence to treat the trust policy
as a resource policy while treating inline policies as an IAM
policy
> Treating trust policy as a resource policy.

- security_monkey/auditor.py
- security_monkey/auditors/elb.py
- security_monkey/auditors/elbv2.py
- security_monkey/auditors/rds/rds_db_cluster.py
- security_monkey/auditors/rds/rds_db_instance.py
- security_monkey/auditors/rds/rds_security_group.py
- security_monkey/auditors/rds/rds_snapshot.py
- security_monkey/tests/auditors/rds/test_rds_db_cluster.py
- security_monkey/tests/auditors/rds/test_rds_db_instance.py
- security_monkey/tests/auditors/rds/test_rds_snapshot.py
- security_monkey/tests/core/test_auditor.py
Auditors specifically look for internet-accessible databases by checking attached security groups.
> Adding RDS Instance/Cluster Auditors and tests.

- dart/web/ui.html
- docs/iam_aws.md
- scripts/secmonkey_role_setup.py
- security_monkey/auditors/ebs_snapshot.py
- security_monkey/watchers/ec2/ebs_snapshot.py
Looks for public/shared EBS snapshots.
TODO:
> Adding EBS Snapshot Auditor.

- setup.py
This change will support Postgressql 10.X
> Change psycopg2 version from 2.6.2 to 2.7.3.2

- security_monkey/watchers/elasticsearch_service.py
* Make ElasticSearch watcher check for None before doing an tuple unpack on ES domain enumeration
> Fix TypeError when not granted es:ListDomainNames

- security_monkey/watchers/elasticsearch_service.py
- setup.py
More ES exception handling fixes.
> Follow-up for #849.

- security_monkey/auditor.py
- security_monkey/auditors/iam/iam_policy.py
Fixing issue #873. IAM Users/Groups/Roles with an attached managed policy with zero issues causing an exception.
> Fixing issue #873

- security_monkey/auditor.py
> Allowing for ranges with multiple hyphens.

- docs/iam_gcp.md
- docs/instance_launch_gcp.md
Added clarifications for GCP IAM.
> IAM improvements to GCP docs.

- env-config/config.py
- security_monkey/reporter.py
- security_monkey/scheduler.py
- setup.py
WIP: Testing the latest version of APScheduler which should hopefully minimize the memory footprint and leakage.
Should hopefully address #903
> 🔺 Upgrading to APScheduler 3.5.0

- security_monkey/watchers/iam/iam_role.py
Fixed bug introduced in batched watcher refactor.
> Removed region from IAM role

- security_monkey/views/item_issue.py
`HTTP 500: {"status": 500, "message": "Internal Server Error”}` on UI client for Reports -> Justified issues, this is after update to latest develop
```
File "/usr/local/src/security_monkey/security_monkey/views/item_issue.py", line 187, in get {'justified_user': issue.user.email}.items())
AttributeError: 'NoneType' object has no attribute ‘email’
```
Solution:
Added missing check for None
> check for user existence

- security_monkey/datastore_utils.py
- security_monkey/task_scheduler/tasks.py
- security_monkey/tests/scheduling/test_celery_scheduler.py
- security_monkey/watcher.py
- security_monkey/watchers/sqs.py
> Fix for orphaned items that may develop from a failed watcher event.

- celeryconfig.py
- docs/autostarting.md
- security_monkey/datastore.py
- security_monkey/exceptions.py
- security_monkey/watchers/vpc/vpn.py
- setup.py
Migrated VPN watcher to CloudAux to fix issues, and also updated the `celeryconfig.py` to include the `timezone` to address bugs with Celery.
Also bumped up CloudAux version to 1.4.6.
> Migrated VPN watcher to CloudAux

- security_monkey/__init__.py
- security_monkey/common/utils.py
- security_monkey/datastore_utils.py
- security_monkey/watcher.py
- Moved SES sender over to boto3
- Fixed an obscure bug in the batched change finder that can result in change finder emails being sent out when nothing actually changed.
> Made Email Fixes 📧

- .travis.yml
- env_tests/test_dart.sh
- security_monkey/cloudaux_batched_watcher.py
- security_monkey/tests/watchers/openstack/__init__.py
- security_monkey/tests/watchers/test_iam_role.py
Array indexing error if an item is listed -- but deleted by the time it's described.
> Batched watcher array bug fix

- .travis.yml
- Dockerfile
- dart/pubspec.yaml
- docker-compose.init.yml
- docker-compose.yml
- docker/api-init.sh
- docker/api-start.sh
- docker/celeryconfig.py
- docker/nginx/Dockerfile
- docker/scheduler-start.sh
- docker/worker-start.sh
- docs/docker.md
- docs/update.md
- Updating from Trusty (14.04 LTS) to Xenial (16.04 LTS)
- Updated the Upgrading instructions to reflect the Celery changes
- Updated Docker compose to use PostgreSQL 10.1
> Updating the Docker files to work with 1.0

- docs/changelog.md
- setup.py
This should be the final PR before 1.0.
> Small updates for 1.0

- docs/changelog.md
- docs/installation/07-load-data.md
> 1.0 release

- docs/installation/01-launch-instance.md
- docs/installation/02-create-db.md
- docs/installation/03-install-sm.md
- docs/installation/04-accounts.md
This *should* fix the paths I broke in my cleanup of the documentation.  Apologies for the broken links.
> Cease all future PRs while holding a crying newborn

- security_monkey/auditors/ebs_snapshot.py
> Fix for #960.

- security_monkey/auditors/ec2_image.py
> Fix for EC2 Image NoneTypes

- security_monkey/manage.py
- security_monkey/tests/utilities/test_user_utils.py
After applying patch:
```
$ monkey create_user "user.name@example.com" "Justify"
Password: 
Confirm Password:
$ monkey create_user "user.name@example.com" "Justify"
[+] Updating existing user
Password: 
Confirm Password:
$
```
> Fix for issue #966.

- security_monkey/tests/utilities/test_user_utils.py
Fixes unit test from #967
Special thanks to @senorcinco for the feature!
> Fixed test from #967

- security_monkey/task_scheduler/beat.py
> Cleaned output for Zero interval

- migrations/versions/bfb550a500ab_.py
- security_monkey/backup.py
- security_monkey/common/PolicyDiff.py
- security_monkey/common/utils.py
- security_monkey/datastore_utils.py
Fixed two kinds of Python 3 Syntax Errors with code that works for both Python 2 and Python 3:
* __print()__ is a function in Python 3
* Old style exceptions --> new style
> print() is a function in modern Python

- security_monkey/watchers/github/org.py
- security_monkey/watchers/github/repo.py
Updated ephemerals for GitHub Orgs and Repos for items that can change frequently.
> Updated ephemerals for GH orgs and repos.

- migrations/versions/bfb550a500ab_.py
- security_monkey/__init__.py
- security_monkey/account_manager.py
- security_monkey/auditor.py
- security_monkey/common/utils.py
- security_monkey/datastore.py
- security_monkey/datastore_utils.py
- security_monkey/sso/views.py
- security_monkey/watcher.py
- setup.py
The syntax errors in #974 prevented flake8 from finding theses issues or they would have been fixed in #977 so now they will be fixed in this PR.
> fix-basestring-unicode-for-Python3-again

- dart/lib/component/account_view_component/account_view_component.html
- docs/dev_setup_osx.md
- migrations/versions/00c1dabdbe85_lengthen_account_name.py
- security_monkey/account_manager.py
- security_monkey/datastore.py
lengthen account.name to 50 characters to match AWS name length
> lengthen account.name to 50 characters to match AWS name length

- setup.py
A continuation of #994
__Not__ upgraded:
* ~~**Flask-Script** from `==0.6.3` to `==2.0.6`~~
* ~~**Flask-SQLAlchemy** `==1.0` to `==2.3.2`~~
* ~~**moto** from `==0.4.30` to `==1.2.0`~~
@mikegrima Please review.
> Updating requirements in setup.py - again

- data/aws_accounts.json
> Update region list

- .travis.yml
- migrations/versions/a9fe9c93ed75_.py
- security_monkey/datastore.py
- security_monkey/watchers/elastic_ip.py
First phase of fixing duplicates in the `issue_item_association` table.
Also added in more ephemerals to the EIP watcher since that was very noisy.
> Duplicate Issue-Item Association Fixes

- docs/issue_template.md
Make it slightly easier for users to comply with bug reporting procedure
> Add link to search for open and closed issues

- docs/installation/06-nginx.md
> Small improvement to Quickstart documentation

- docker-compose.yml
- docs/docker.md
- docs/installation/04-accounts.md
Add note about creds files. Also adding clarification for role_name for AWS account creation.
> Minor updates to docker documentation

- security_monkey/manage.py
- security_monkey/task_scheduler/beat.py
- security_monkey/task_scheduler/tasks.py
- security_monkey/tests/scheduling/test_celery_scheduler.py
Looking to find source of some phantom exceptions that are apparently in the SQS watcher.
EDIT: Believe this is related to it trying to hit the Gov region. An update for this is in #1009 .
> Tweaks and fixes

- docs/installation/03-install-sm.md
- docs/instance_launch_gcp.md
this is a pull request for issue #1023
> Documentation Suggestion on Ubuntu 16.04 Issue Number 1023

- security_monkey/views/item.py
When Active is selected it should show results only from Active Account
> Fixes #872

- migrations/versions/11f081cf54e2_.py
Resolves DB duplicated identified in #1028 .
Please run `monkey db upgrade` after pulling this down.
> Fix for #1028

- docs/instance_launch_aws.md
- docs/options.md
- docs/quickstart.md
After taking a pass through the current docs and getting started
guidance I have made a few changes to correct some things that
are out of date and explicitly mentioned that the quickstart
guide isn't adequate for production deployments.
> Updating Security Monkey Docs

- README.md
- dart/pubspec.yaml
- docs/iam_aws.md
- env-config/config-docker.py
- env-config/config.py
- security_monkey/__init__.py
- security_monkey/cloudaux_watcher.py
- security_monkey/tests/watchers/openstack/__init__.py
- security_monkey/tests/watchers/openstack/object_store/test_object_container.py
- security_monkey/watchers/security_group.py
- security_monkey/watchers/vpc/vpc.py
- setup.py
Better VPC watching support.
NEW PERMISSIONS REQUIRED
> VPC watcher moved over to CloudAux

- security_monkey/auditors/vpc/vpc.py
> VPC Flow Log audit fixes.

- docs/github_setup.md
Updated the GitHub documents to address #1027.
> Updated GH docs for clarity

- docs/issue_template.md
Fixed the broken links in the issue template.
> Fixed links in the issue template.

- dart/pubspec.yaml
- docker/nginx/Dockerfile
- security_monkey/__init__.py
Roll-up release to address issues with PyPI and Docker builds with Ubuntu Bionic Beaver.
> Roll-up for 1.1.1

- migrations/versions/00c1dabdbe85_lengthen_account_name.py
- migrations/versions/7c54b06e227b_.py
- security_monkey/datastore.py
- security_monkey/exceptions.py
- security_monkey/tests/core/test_datastore_utils.py
Fixing errors where duplicates in the database break things.
Will also create a migration script to detect and fix these.
> Fixing duplicate item errors.

- docs/postgres_gcp.md
I added some more details on setting up cloud_sql_proxy
- added enabling cloud sql api
- added creating a service account
- updated the psql command
- added a link for setting up the db
> Gcp doc updates

- security_monkey/auditor.py
- security_monkey/auditors/iam/managed_policy.py
- security_monkey/datastore.py
- security_monkey/tests/core/test_audit_issue_cleanup.py
- security_monkey/views/item_issue.py
Fixes #1063 
@monkeysecurity  We will need to revisit this when we make issue improvements in the future.
> Fixes for duplicate item audit issues

- env-config/config-local.py
- env-config/config.py
- migrations/versions/7c54b06e227b_.py
- security_monkey/auditor.py
- security_monkey/tests/core/test_watcher.py
- security_monkey/watcher.py
> Fix for DB error documented in #1005

- requirements.txt
- security_monkey/manage.py
> Updated SWAG sync to reference the top-level account status field

- requirements.txt
> Upgraded celery to latest RC (RC4).
